# Linear Algebra in Python

This is part of a tutorial from *University of British Columbia*
<a href="https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/eigenvalues-eigenvectors/"> Eigenvalues</a>

## **Eigenvalues & Eigenvectors**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

Definition:

Let $A$ be a square matrix. A non-zero vector $\mathbf{v}$ is an eigenvector for $A$ with eigenvalue $\lambda$ if

$$ A\mathbf{v} = \lambda \mathbf{v} $$

Rearranging the equation, we see that $\mathbf{v}$ is a solution of the homogeneous system of equations

$$ \left( A - \lambda I \right) \mathbf{v} = \mathbf{0} $$

where $I$ is the identity matrix of size $n$. Non-trivial solutions exist only if the matrix $A - \lambda I$ is singular which means $\mathrm{det}(A - \lambda I) = 0$. Therefore eigenvalues of $A$ are roots of the characteristic polynomial

$$ p(\lambda) = \mathrm{det}(A - \lambda I) $$

### *Diagonal matrix* and ``la.eig()``
- The function la.eig returns a tuple (eigvals,eigvecs) where eigvals is a 1D NumPy array of complex numbers giving the eigenvalues of A 
- eigvecs is a 2D NumPy array with the corresponding eigenvectors in the columns

In [53]:
A = np.array([
    [np.random.randint(6), np.random.randint(6)],
    [np.random.randint(6), np.random.randint(6)] 
])
print(A,'\n')

# eigen
eig = la.eig(A)
print(f'Eigenvalues: \n{eig[0]}\n')
print(f'Eigenvectors: \n{eig[1]}\n')

[[4 3]
 [4 5]] 

Eigenvalues: 
[1.+0.j 8.+0.j]

Eigenvectors: 
[[-0.70710678 -0.6       ]
 [ 0.70710678 -0.8       ]]



IF eigenvalues are Real, Then you can use the ``.real`` tp convert eigenvalues to real numbers

In [54]:
eigvals, eigvecs = la.eig(A)
eigvals = eigvals.real

print(eigvals)
egg1 = eigvals[0]
print(egg1)

[1. 8.]
1.0


In [55]:
# print out the eigenvectors
print('\n Eigenvectors\n',eigvecs)
# 
v1 = eigvecs[:,1] # get just column 1
print('\n v[: ,1]\n',v1)

# reshape column 1
v1 = eigvecs[:,1].reshape(2,1)
print('\n v[:,1].reshape\n',v1)


 Eigenvectors
 [[-0.70710678 -0.6       ]
 [ 0.70710678 -0.8       ]]

 v[: ,1]
 [-0.6 -0.8]

 v[:,1].reshape
 [[-0.6]
 [-0.8]]


In [56]:
print(A)
print('\n v[:,1].reshape\n',v1)

print(f'\nMultiplication A@v1 \n{ A@v1 }')

[[4 3]
 [4 5]]

 v[:,1].reshape
 [[-0.6]
 [-0.8]]

Multiplication A@v1 
[[-4.8]
 [-6.4]]


## Symmetric Matrix

- symmetric matrix Eigenvalues are *always real* and *always orthogonal* 

In [110]:
n = np.random.randint(1,6)
w= np.random.randint(1,6,(n,n))
print(f'w\n{w}','\n')

print(f'Transpose: \n{w.T},\n')

# symmetrix matrix, with Transpose
symM = w@w.T
print(f'w@w.T \n {symM}')

w
[[2 1 5]
 [3 5 5]
 [2 4 4]] 

Transpose: 
[[2 3 2]
 [1 5 4]
 [5 5 4]],

w@w.T 
 [[30 36 28]
 [36 59 46]
 [28 46 36]]


In [115]:
# get the eigenvalues, vectors 
evals, evects = la.eig(w)

# use the .real to drop the complex values
print(f'eigenvalues.real: {evals.real}')

print(f'eigenvectors.real \n {evects.real}')

eigenvalues.real: [10.59948562  0.20025719  0.20025719]
eigenvectors.real 
 [[ 0.40955697 -0.88099884 -0.88099884]
 [ 0.71985159  0.22361284  0.22361284]
 [ 0.56042554  0.2723917   0.2723917 ]]


In [117]:
# orthogonal check
v1 = evects[:,0]
print(f'v1: {v1.real}')
v2 = evects[:,1]
print(f'v2: {v2.real}')

# the @
vm = v1@v2
print(f'v1@v2: \n{vm.real}')

v1: [0.40955697 0.71985159 0.56042554]
v2: [-0.88099884  0.22361284  0.2723917 ]
v1@v2: 
-0.047195896188857445


## Diagonals ``np.diag(r,c)``

A square matrix $M$ is diagonalizable if it is similar to a diagonal matrix. In other words, $M$ is diagonalizable if there exists an invertible matrix $P$ such that $D = P^{-1}MP$ is a diagonal matrix.

A beautiful result in linear algebra is that a square matrix $M$ of size $n$ is diagonalizable if and only if $M$ has $n$ independent eigevectors. Furthermore, $M = PDP^{-1}$ where the columns of $P$ are the eigenvectors of $M$ and $D$ has corresponding eigenvalues along the diagonal.

Let's use this to construct a matrix with given eigenvalues $\lambda_1 = 3, \lambda_2 = 1$, and eigenvectors $v_1 = [1,1]^T, v_2 = [1,-1]^T$.

In [134]:
h = np.array([
    [1,1],[1,-1]])
print(h)

print(f'\ninv(h)\n{la.inv(h)}')

d = np.diag((3,1))
print(f'\n np.diag():\n{d}')

M = h @ d @ la.inv(h)
print('\n',M)

[[ 1  1]
 [ 1 -1]]

inv(h)
[[ 0.5  0.5]
 [ 0.5 -0.5]]

 np.diag():
[[3 0]
 [0 1]]

 [[2. 1.]
 [1. 2.]]


### *trust* **but verify** that eigenvalues are *M* are 3 and 1

In [136]:
evals, evecs = la.eig(M)
print(evals.real)
print(evecs.real)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
