# **Linear Algebra** using SciPy

This is a tutorial from *University of British Columbia*

<a href="https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/"> Linear Algebra with SciPy</a>

- *Images are not part of the tutorial*

![matrix](matrix-banner.png)

In [1]:
import numpy as np
import scipy.linalg as la

## NumPy Arrays

- 1D is like a list [ ]
- 2D is a latrix
- 3D is a cube of numbers {rubix cube}

In [9]:
# 1D array, a range of numbers 1 to 9
arr1 = np.arange(1,10)
print(f'1D: {arr1}')

# get the dimension
print(f'Dimension: {arr1.ndim}')

# get the shape of array, 
# returns (rows, columns)
print(f'Shape: {arr1.shape}')

1D: [1 2 3 4 5 6 7 8 9]
Dimension: 1
Shape: (9,)


In [32]:
# 2D array / Matrix
matrx = np.array([
    [np.random.randint(10), np.random.randint(10)],
    [np.random.randint(10), np.random.randint(10)],
    [np.random.randint(10), np.random.randint(10)]
])
print(f'Matrix: \n{matrx}')

print(f'\nDimension: {matrx.ndim}')
print(f'Shape: {matrx.shape}')
print(f'Number of elements in array: {matrx.size}')

Matrix: 
[[8 2]
 [1 4]
 [3 5]]

Dimension: 2
Shape: (3, 2)
Number of elements in array: 6


column slice

In [42]:
print(f'matrix: \n{matrx}\n')

# get column 1 (not the 1st column) by slicing
col = matrx[:,1]
print(f'column 1: {col}')
print(f'Shape: {col.shape}')
print(f'Dimension: {col.ndim}')
print(f'Size: {matrx.size}')

matrix: 
[[8 2]
 [1 4]
 [3 5]]

column 1: [2 4 5]
Shape: (3,)
Dimension: 1
Size: 6


reshape the column using ``reshape(r,c)``

In [45]:
# as is column
print(f'column 1: {col}\n')

# reshaped column
print(col.reshape(3,1)) 

column 1: [2 4 5]

[[2]
 [4]
 [5]]


## Level Up: Matrix Operations and Functions
- image not part of tutorial
![image not part of tutorial](matrix-ops.jpg)

In [53]:
M = np.array([
    [np.random.randint(7), np.random.randint(7)],
    [np.random.randint(7), np.random.randint(7)]
])
print(M)

# multiply a matrix by itself
print('\n M*M \n', M*M)

[[4 0]
 [4 4]]

 M*M 
 [[16  0]
 [16 16]]


## The next level: matrix multiplication using ``@``

In [54]:
M@M

array([[16,  0],
       [32, 16]])

**NumPy** has identity matrix ``np.eye(n)`` for easy identity matrix
- $n$ is the size of rows and columns

Note: $2I$ is **identity matrix** of size 2

Let's compute $2I + 3A - AB$ for

$$ A = \begin{bmatrix} 1 & 3 \\ -1 & 7 \end{bmatrix} \ \ \ \ B = \begin{bmatrix} 5 & 2 \\ 1 & 2 \end{bmatrix} $$

In [62]:
A = np.array([[1,3],[-1,7]])
B = np.array([[5,2],[1,2]])
I = np.eye(2)

print('Matrix A:\n',A)
print('\nMatrix B:\n',B)
print('\nIdentity: \n', I)

Matrix A:
 [[ 1  3]
 [-1  7]]

Matrix B:
 [[5 2]
 [1 2]]

Identity: 
 [[1. 0.]
 [0. 1.]]


In [64]:
# now do the calculations
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

## Level Up: Matrix **POWERS** ``matrix_power``

In [86]:
from numpy.linalg import matrix_power as mpow

# for laziness, elements for matrix
e1 = np.random.randint(10)
e2 = np.random.randint(10)
e3 = np.random.randint(10)
e4 = np.random.randint(10)

# create a matrix with elements
M = np.array([
    [e1,e2],
    [e3,e4],
])
print(f'Matrix:\n{M}')
# matrix^2
print(f'\nMatrix POWER!:\n{mpow(M,2)}')

Matrix:
[[9 1]
 [4 7]]

Matrix POWER!:
[[85 16]
 [64 53]]


In [87]:
print(M)
# matrix^5
print(f'\nMatrix POWER!:\n{mpow(M,5)}')

[[9 1]
 [4 7]]

Matrix POWER!:
[[83073 23705]
 [94820 35663]]


In [90]:
# inefficient method of matrix power
M @ M @ M @ M @ M

array([[83073, 23705],
       [94820, 35663]])

## Next Level: **Transpose** a matrix  ``.T``

In [93]:
print(M,'\n')

print('Transposed\n', M.T)

[[9 1]
 [4 7]] 

Transposed
 [[9 4]
 [1 7]]


## Next level:  Inverse a matrix
- ``scipy.linalg.inv``

In [99]:
print(f'matrix A: \n{A}\n')
print(f'matrix la.inv(A) : \n{la.inv(A)}')

matrix A: 
[[ 1  3]
 [-1  7]]

matrix la.inv(A) : 
[[ 0.7 -0.3]
 [ 0.1  0.1]]


## Next Level: Trace ``np.trace``

- A trace is defined to be the sum of elements on the main diagonal (from the upper left to the lower right) of A.

In [105]:
print(f'matrix A: \n{A}\n')
print(f'matrix np.trace(A): {np.trace(A)}')

matrix A: 
[[ 1  3]
 [-1  7]]

matrix np.trace(A): 8


## Level Up: Determinant ``scipy.linalg.det``

\begin{aligned}|A|={\begin{vmatrix}a&b\\c&d\end{vmatrix}}=ad-bc.\end{aligned}

Determinant is a scalar value that is a function of the entries of a square matrix.  
The determinant is nonzero if and only if the matrix is invertible.

In [106]:
print(f'matrix A: \n{A}\n')
print(f'matrix la.det(A) : \n{la.det(A)}')

matrix A: 
[[ 1  3]
 [-1  7]]

matrix la.det(A) : 
10.0


## Polynomials and Cayley-Hamilton Theorem 

Characteristic Polynomials and Cayley-Hamilton Theorem
The characteristic polynomial of a 2 by 2 square matrix $A$ is

$$ p_A(\lambda) = \det(A - \lambda I) = \lambda^2 - \mathrm{tr}(A) \lambda + \mathrm{det}(A) $$

The Cayley-Hamilton Theorem states that any square matrix satisfies its characteristic polynomial. For a matrix $A$ of size 2, this means that

$$ p_A(A) = A^2 - \mathrm{tr}(A) A + \mathrm{det}(A) I = 0 $$

In [116]:
trace_A = np.trace(A)
print('trace A ',trace_A,'')

det_A = la.det(A)
print('det_A ',det_A,'')

I = np.eye(2)
print('I\n',I)

CHT = A @ A - trace_A * A + det_A * I
print('\n',CHT)

trace A  8 
det_A  10.0 
I
 [[1. 0.]
 [0. 1.]]

 [[0. 0.]
 [0. 0.]]


This concludes this lesson. 