# **Linear Algebra** in Python

Resource: *University of British Columbia*
- https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In matrix notation, a linear system is $A \mathbf{x}= \mathbf{b}$ where

$$ A = \begin{bmatrix} a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\ a_{1,0} & a_{1,1} & \cdots & a_{1,n} \\ \vdots & & & \vdots \\ a_{m,0} & a_{m,1} & \cdots & a_{m,n} \\ \end{bmatrix} \ \ , \ \ \mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \\ \vdots \\ x_n \end{bmatrix} \ \ , \ \ \mathbf{b} = \begin{bmatrix} b_0 \\ b_1 \\ \vdots \\ b_m \end{bmatrix} $$

## Solving Linear Systems 

In [5]:
A = np.array([[1,1,2],
              [-1,3,1],
              [0,5,2]])
print(A)

E1 = np.array([[1,0,3],
               [0,1,0],
               [0,0,1]])
print('\n',E1) 

[[ 1  1  2]
 [-1  3  1]
 [ 0  5  2]]

 [[1 0 3]
 [0 1 0]
 [0 0 1]]


To multiply $k$ times row $i$ in a matrix $A$, we multiply $A$ by the matrix $E$ where $E$ is equal to the identity matrix except the $,i,j$ entry is $E_{i,i} = k$. 

For example, if $A$ is 3 by 3 and we want to multiply row 1 by -2 then

$$ E_2 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 1 \end{bmatrix} $$

In [9]:
E2 = np.array([[1,0,0],[0,-2,0],[0,0,1]])
print(E2)

# multiply each row by -2, using the @
print('\n E2@A\n',E2@A)

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0  1]]

 E2@A
 [[ 1  1  2]
 [ 2 -6 -2]
 [ 0  5  2]]


For example, if $A$ is 3 by 3 and we want to switch row 1 and row 2 then

$$ E^3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 1 & 0 \end{bmatrix} $$

In [12]:
# instead of typing out your array for Idnetity matrix
# use the np.eye() function

E3 = np.eye(3)
print(E3)

# matrix multiplication
print('\n E3@A\n', E3@A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 E3@A
 [[ 1.  1.  2.]
 [-1.  3.  1.]
 [ 0.  5.  2.]]


write a function called add_rows which takes input parameters $A$, $k$, $i$ and $j$ and returns the NumPy array resulting from adding $k$ times row $j$ to row $i$ in the matrix $A$. 

If $i=j$, then let's say that the function scales row $i$ by $k+1$ since this would be the result of $k$ times row $i$ added to row $i$.

In [13]:
def add_row(A,k,i,j):
    "Add k times row j to row i in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

In [19]:
# let's generate random values for a 2x2 matrix 
# 
M = np.random.randint(1,50,(2,2))
print(M)

# generate random values ofr k,i,j
k = np.random.randint(0,3)
i = np.random.randint(0,3)
j = np.random.randint(0,3)

# call the add_row() function
add_row(M, k, i, j) 

[[41  9]
 [48 29]]


array([[89., 38.],
       [48., 29.]])

write a function called scale_row which takes 3 input parameters $A$, $k$, and $i$ and returns the matrix that results from $k$ times row $i$ in the matrix $A$.

In [132]:
def scale_row(M,k,i):
    "Multiply row i by k in matrix A."
    n = M.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ M

In [134]:
# M = np.array([[3,1],[-2,7]])
M = np.random.randint(1,50,(2,2))
print(M)

i = 3
j = 1
scale_row(M, i, j)

[[25 34]
 [28 38]]


array([[ 25.,  34.],
       [ 84., 114.]])

In [136]:
M = np.random.randint(1,10,(3,3))
print(M)

i = np.random.randint(5)
j = np.random.randint(3)

scale_row(M, i, j)

[[1 2 5]
 [8 5 1]
 [5 7 3]]


array([[ 4.,  8., 20.],
       [ 8.,  5.,  1.],
       [ 5.,  7.,  3.]])

function called switch_rows which takes 3 input parameters $A$, $i$ and $j$ and returns the matrix that results from switching rows $i$ and $j$ in the matrix $A$.

In [131]:
def switch_rows(M,i,j):
    "Switch rows i and j in matrix A."
    n = M.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ M

In [181]:
M= np.array([
    np.arange(0,4),
    np.arange(4,8)
])
print(M,":" ,M.shape) # show the rows, columns

i = np.random.randint(2) # change the value and get an error
j = np.random.randint(2)
print('\n',i,':',j)

# call the switch_rows
switch_rows(M,i,j)

[[0 1 2 3]
 [4 5 6 7]] : (2, 4)

 1 : 0


array([[4., 5., 6., 7.],
       [0., 1., 2., 3.]])

functions to the augmented matrix $[M \ | \ I]$ to find the inverse of the matrix $M$:

In [198]:
M= np.array([
    np.arange(-4,-1),
    np.arange(-7,-4),
    np.arange(9,12)
])
print(M,":",M.shape) 

# hstack= horizontal stack
#  adds identity matrix to existing matrix
A = np.hstack([M , np.eye(3)])
print('\n',A)

[[-4 -3 -2]
 [-7 -6 -5]
 [ 9 10 11]] : (3, 3)

 [[-4. -3. -2.  1.  0.  0.]
 [-7. -6. -5.  0.  1.  0.]
 [ 9. 10. 11.  0.  0.  1.]]


In [206]:
print('\n',A)
A1 = switch_rows(A,i,j)
print('\n',A1) 


 [[-4. -3. -2.  1.  0.  0.]
 [-7. -6. -5.  0.  1.  0.]
 [ 9. 10. 11.  0.  0.  1.]]

 [[-7. -6. -5.  0.  1.  0.]
 [-4. -3. -2.  1.  0.  0.]
 [ 9. 10. 11.  0.  0.  1.]]


In [202]:
A2 = add_row(A1,i,j,k)
print(A2)

[[-11.  -9.  -7.   1.   1.   0.]
 [ -4.  -3.  -2.   1.   0.   0.]
 [  9.  10.  11.   0.   0.   1.]]


In [204]:
A3 = add_row(A2,i,j,k)
A4 = switch_rows(A3,i,j)
print(A4)

[[ -4.  -3.  -2.   1.   0.   0.]
 [-15. -12.  -9.   2.   1.   0.]
 [  9.  10.  11.   0.   0.   1.]]


functions to perform Gaussian elimination and solve a linear system of equations $A \mathbf{x} = \mathbf{b}$.

In [222]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
print(A)

b = np.array([[2],[14],[10]])
print('\n',b) 

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]

 [[ 2]
 [14]
 [10]]


In [223]:
x = la.solve(A,b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [224]:
M = np.hstack([A,b])
print('\n Adding b to A\n',M)

f = np.random.randn(1)
print('\n',f)

M1 = scale_row(A, f, j)
print('\n',M1)


 Adding b to A
 [[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]

 [0.11467686]

 [[ 0.68806117  1.72015292  0.11467686]
 [ 8.          7.         12.        ]
 [ 2.          7.          8.        ]]


mostly interested in linear systems $A \mathbf{x} = \mathbf{b}$ where there is a unique solution $\mathbf{x}$. This is the case when $A$ is a square matrix ($m=n$) and $\mathrm{det}(A) \not= 0$. 

To solve such a system, we can use the function ``scipy.linalg.solve.``

In [226]:
A = np.array([[1,1],[1,-1]])
print(A)

b1 = np.array([2,0])
print('\n',b1)

x1 = la.solve(A,b1)
print('\n la.solve()\n',x1)

[[ 1  1]
 [ 1 -1]]

 [2 0]

 la.solve()
 [1. 1.]


 If we input $\mathbf{b}$ as a 2D NumPy array, then the output is a 2D NumPy array.

In [227]:
A = np.array([[1,1],[1,-1]])
b2 = np.array([2,0]).reshape(2,1)
x2 = la.solve(A,b2)
print(x2)

[[1.]
 [1.]]


compute the solution of the system of equations

\begin{align} 2x + y &= 1 \\ x + y &= 1 \end{align}

Create the matrix of coefficients:

In [231]:
A = np.array([[2,1],[1,1]])
print(A)

# vector
b = np.array([1,-1]).reshape(2,1)
print('\n',b)

# la.solve() 
x = la.solve(A,b)
print('\n la.solve()\n',x)

# inverse
Ainv = la.inv(A)
print('\n inverse\n',Ainv)

# multiply A inverse to solve x
x = Ainv @ b
print('\n A inverse\n',x)

[[2 1]
 [1 1]]

 [[ 1]
 [-1]]

 la.solve()
 [[ 2.]
 [-3.]]

 inverse
 [[ 1. -1.]
 [-1.  2.]]

 A inverse
 [[ 2.]
 [-3.]]


It's a bad idea to use the inverse $A^{-1}$ to solve $A \mathbf{x} = \mathbf{b}$ if $A$ is large. It's too computationally expensive. Let's create a large random matrix $A$ and vector $\mathbf{b}$ and compute the solution

USE ``scipy.linalg.solve`` 